___
# Ciência dos Dados - PROJETO 1

## COLOQUE AQUI SEU NOME
___

## TÍTULO DO SEU PROJETO

___
## Introdução

Descreva aqui o que pretende analisar!

Capriche no português!! 
Se quiser pode utilizar pesquisas semelhantes publicadas em sites confiáveis!!

___
## Análise e Resultados

In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [2]:
print('Esperamos trabalhar no diretório')
print(os.getcwd())

Esperamos trabalhar no diretório
C:\Users\vitor\Documents\SegundoSemestre\CienciasDosDados\CienciaDosdados2.0

In [3]:
#Se usar o arquivo descompactado
#pd.read_csv('DOM2015.csv',sep=',')

#Se usar o arquivo compactado como está no dropbox púbico
#pd.read_csv('DOM2015csv.zip', compression='zip', header=0, sep=',', quotechar='"')
dados =pd.read_csv('DOM2009csv.zip', compression='zip', header=0, sep=',', quotechar='"')
dados.head()

,Unnamed: 0,V0101,UF,V0102,V0103,V0104,V0105,V0106,V0201,V0202,...,V2136,V2033,V2034,V2035,V2036,V2037,V2038,V2039,V2041,V9992
0,0,2009,11,15,1,8,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20120710
1,1,2009,11,15,2,8,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20120710
2,2,2009,11,15,3,1,7.0,5.0,1.0,2.0,...,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,20120710
3,3,2009,11,15,4,1,3.0,3.0,1.0,2.0,...,NaN,3.0,3.0,1.0,3.0,3.0,3.0,3.0,3.0,20120710
4,4,2009,11,15,5,1,1.0,1.0,1.0,2.0,...,NaN,3.0,3.0,3.0,1.0,3.0,3.0,3.0,3.0,20120710

In [4]:
dadosPR = dados[dados.UF == 41].loc[:,["V0101","UF","V0228","V0229","V4622","V2103","V2111"]]
dadosPR = dadosPR[pd.notnull(dados.V0228)]
dadosPR.to_csv("dadosRESUMO.csv")
dadosPR

C:\Users\vitor\Documents\Anaconda-Phython\lib\site-packages\ipykernel\__main__.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  from ipykernel import kernelapp as app

        V0101  UF  V0228  V0229  V4622  V2103  V2111
112228   2009  41    4.0    3.0    4.0    3.0    NaN
112229   2009  41    4.0    3.0    3.0    3.0    NaN
112230   2009  41    4.0    1.0    4.0    3.0    NaN
112231   2009  41    2.0    3.0    2.0    3.0    NaN
112232   2009  41    2.0    3.0    4.0    3.0    NaN
112233   2009  41    4.0    3.0    4.0    3.0    NaN
112234   2009  41    4.0    3.0    3.0    3.0    NaN
112235   2009  41    4.0    3.0    3.0    1.0    1.0
112236   2009  41    2.0    3.0    4.0    3.0    NaN
112238   2009  41    4.0    3.0    3.0    3.0    NaN
112239   2009  41    2.0    3.0    2.0    1.0    3.0
112240   2009  41    4.0    3.0    3.0    3.0    NaN
112241   2009  41    4.0    3.0    3.0    3.0    NaN
112242   2009  41    2.0    1.0    3.0    3.0    NaN
112243   2009  41    2.0    3.0    3.0    3.0    NaN
112244   2009  41    2.0    3.0    3.0    1.0    3.0
112245   2009  41    4.0    3.0    0.0    3.0    NaN
112246   2009  41    4.0    3.0    4.0    1.0    3.0
112247   2009  41    4.0    3.0    2.0    3.0    NaN
112248   2009  41    4.0    3.0    4.0    3.0    NaN
112249   2009  41    4.0    3.0    3.0    3.0    NaN
112250   2009  41    4.0    3.0    4.0    3.0    NaN
112251   2009  41    2.0    3.0    3.0    3.0    NaN
112252   2009  41    4.0    3.0    4.0    3.0    NaN
112253   2009  41    4.0    3.0    4.0    3.0    NaN
112255   2009  41    4.0    3.0    3.0    3.0    NaN
112256   2009  41    2.0    1.0    5.0    3.0    NaN
112260   2009  41    2.0    3.0    3.0    1.0    1.0
112261   2009  41    4.0    3.0    3.0    3.0    NaN
112262   2009  41    2.0    3.0    5.0    3.0    NaN
...       ...  ..    ...    ...    ...    ...    ...
119792   2009  41    4.0    3.0    4.0    3.0    NaN
119795   2009  41    2.0    3.0    7.0    3.0    NaN
119796   2009  41    4.0    3.0    3.0    3.0    NaN
119797   2009  41    4.0    1.0    3.0    1.0    3.0
119798   2009  41    4.0    3.0    4.0    3.0    NaN
119799   2009  41    4.0    3.0    3.0    3.0    NaN
119800   2009  41    4.0    3.0    7.0    3.0    NaN
119802   2009  41    2.0    3.0    1.0    1.0    3.0
119803   2009  41    4.0    3.0    7.0    3.0    NaN
119804   2009  41    2.0    3.0    7.0    3.0    NaN
119805   2009  41    4.0    3.0    6.0    3.0    NaN
119806   2009  41    2.0    3.0    4.0    3.0    NaN
119807   2009  41    2.0    3.0    5.0    3.0    NaN
119808   2009  41    2.0    3.0    4.0    3.0    NaN
119811   2009  41    4.0    3.0    4.0    1.0    1.0
119812   2009  41    2.0    1.0    7.0    3.0    NaN
119813   2009  41    2.0    3.0    7.0    3.0    NaN
119815   2009  41    2.0    3.0    4.0    3.0    NaN
119816   2009  41    2.0    3.0    7.0    3.0    NaN
119817   2009  41    2.0    3.0    7.0    3.0    NaN
119819   2009  41    4.0    3.0    4.0    3.0    NaN
119820   2009  41    2.0    3.0    3.0    1.0    3.0
119821   2009  41    4.0    3.0    5.0    3.0    NaN
119823   2009  41    4.0    3.0    4.0    3.0    NaN
119824   2009  41    2.0    3.0    5.0    3.0    NaN
119825   2009  41    2.0    3.0    3.0    3.0    NaN
119827   2009  41    2.0    3.0    4.0    3.0    NaN
119828   2009  41    2.0    3.0    5.0    3.0    NaN
119829   2009  41    2.0    3.0    3.0    3.0    NaN
119831   2009  41    4.0    3.0    6.0    3.0    NaN

[6378 rows x 7 columns]

___
## Conclusão

Descreva aqui suas conclusões!